#!/usr/bin/env python3
"""
GitHub Actions script to call DocWizard API and generate documentation.
Checks OpenRouter rate limits and skips if approaching daily limit.
"""

import os
import json
import sys
import time
from pathlib import Path
import requests

# Environment variables
OPENROUTER_API_KEY = os.getenv('OPENROUTER_API_KEY')
DOCWIZARD_API_URL = os.getenv('DOCWIZARD_API_URL')
GITHUB_REPOSITORY = os.getenv('GITHUB_REPOSITORY')
GITHUB_SERVER_URL = os.getenv('GITHUB_SERVER_URL', 'https://github.com')

# Validate required vars
if not OPENROUTER_API_KEY:
    print("❌ Error: OPENROUTER_API_KEY secret not set")
    sys.exit(1)

if not DOCWIZARD_API_URL:
    print("❌ Error: DOCWIZARD_API_URL secret not set")
    sys.exit(1)

repo_url = f"{GITHUB_SERVER_URL}/{GITHUB_REPOSITORY}"
print(f"🔍 Generating docs for: {repo_url}")

# Step 1: Check rate limits before proceeding
print("\n📊 Checking OpenRouter API rate limits...")
headers = {
    'Authorization': f'Bearer {OPENROUTER_API_KEY}',
    'HTTP-Referer': 'https://github.com/actions',
    'X-Title': 'DocWizard-GitHubAction'
}

# Make a minimal request to check headers
try:
    check_response = requests.post(
        f"{DOCWIZARD_API_URL}/health",
        headers=headers,
        timeout=10
    )
except Exception as e:
    print(f"⚠️ Could not reach DocWizard API: {e}")
    print("Skipping documentation generation")
    sys.exit(0)

# Check rate limit headers from OpenRouter
remaining = check_response.headers.get('x-ratelimit-remaining-requests')
if remaining:
    try:
        remaining = int(remaining)
        print(f"✓ Rate limit remaining: {remaining} requests")
        
        if remaining < 10:
            print(f"⚠️ Rate limit warning: Only {remaining} requests remaining today!")
            print("Skipping documentation generation to preserve rate limit")
            sys.exit(1)  # Exit with error to trigger the notification step
    except ValueError:
        pass

# Step 2: Call generate-docs endpoint
print(f"\n🚀 Calling {DOCWIZARD_API_URL}/generate-docs...")
try:
    response = requests.post(
        f"{DOCWIZARD_API_URL}/generate-docs",
        json={"repo_url": repo_url},
        headers=headers,
        timeout=600,
        stream=True
    )
except Exception as e:
    print(f"❌ API request failed: {e}")
    sys.exit(1)

if response.status_code != 200:
    print(f"❌ API returned status {response.status_code}")
    error_data = response.text[:200]
    print(f"Response: {error_data}")
    sys.exit(1)

# Step 3: Process streaming response and build documentation
print("\n📝 Processing documentation stream...")
docs_folder = Path("docs")
docs_folder.mkdir(exist_ok=True)

api_ref_path = docs_folder / "API_REFERENCE.md"
file_count = 0

with open(api_ref_path, 'w') as f:
    f.write("# API Reference\n\n")
    f.write(f"Auto-generated by DocWizard for: {repo_url}\n")
    f.write(f"Generated at: {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime())}\n\n")
    f.write("---\n\n")
    
    try:
        for line in response.iter_lines():
            if not line:
                continue
            
            try:
                data = json.loads(line)
                
                if data.get('status') == 'file_processed':
                    file_info = data.get('file', {})
                    filename = file_info.get('filename')
                    doc = file_info.get('documentation')
                    
                    if doc:
                        f.write(f"## 📄 {filename}\n\n")
                        f.write(doc)
                        f.write("\n\n---\n\n")
                        file_count += 1
                        print(f"  ✓ Processed {filename}")
                
                elif data.get('status') == 'rate_limit':
                    print(f"  ⚠️ {data.get('message')}")
                
                elif data.get('status') == 'error':
                    print(f"  ❌ Error: {data.get('message')}")
                    sys.exit(1)
            
            except json.JSONDecodeError:
                continue
    
    except requests.exceptions.RequestException as e:
        print(f"❌ Stream error: {e}")
        sys.exit(1)

print(f"\n✅ Documentation generated successfully!")
print(f"📁 Saved to: {api_ref_path}")
print(f"📊 Total files processed: {file_count}")
